myapp/cloud/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import views

urlpatterns = [
    path('', views.Cloud.as_view(), name='cloud'),
    path('video/', views.CloudVideo.as_view(), name='cloud_video'),
    path('delete/video/<int:id>', views.DeleteVideoFile.as_view(), name='delete_cloud_video'),
    path('delete/video/', csrf_exempt(views.DeleteVideoFile.as_view()), name='delete_cloud_batch_video'),
    path('photo/', views.CloudPhoto.as_view(), name='cloud_photo'),
    path('delete/photo/<int:id>', views.DeletePhotoFile.as_view(), name='delete_cloud_photo'),
    path('delete/photo/', csrf_exempt(views.DeletePhotoFile.as_view()), name='delete_cloud_batch_photo'),
    path('doc/', views.CloudDoc.as_view(), name='cloud_doc'),
    path('delete/doc/<int:id>', views.DeleteDocFile.as_view(), name='delete_cloud_doc'),
    path('delete/doc/', csrf_exempt(views.DeleteDocFile.as_view()), name='delete_cloud_batch_doc'),
    path('archive/', views.CloudArchive.as_view(), name='cloud_archive'),
    path('delete/archive/<int:id>', views.DeleteArchiveFile.as_view(), name='delete_cloud_archive'),
    path('delete/archive/', csrf_exempt(views.DeleteArchiveFile.as_view()), name='delete_cloud_batch_archive'),
    path('storage/', login_required(views.CloudStorage.as_view()), name='cloud_storage'),
    path('thumbnails/', login_required(views.Thumbnailer.as_view()), name='thumbnails'),
]

myapp/main/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index),
    path('profile', views.profileView, name='profile'),
    path('/', include('lightlist_auth.urls')),
    path('family/', views.FamilyView.as_view(), name='family'),
    path('add_family', views.CreateFamily.as_view(), name='add_family'),
    path('delete_family/<int:id>', views.DeleteFamily.as_view(), name='delete_family'),
    path('editprofile/', views.EditProfile.as_view(), name='editprofile'),
    path('family_request/', views.JoinFamilyRequestView.as_view(), name='join_family'),
    path('process_request/', views.ProcessRequest.as_view(), name='process_request'),
    path('accept_request/<int:id>', views.AcceptRequest.as_view(), name='accept_request'),
    path('decline_request/<int:id>', views.DeclineRequest.as_view(), name='decline_request'),
    path('productlist/', include('product_list.urls')),
    path('exit_from_group/<int:id>', views.ExitFromGroup.as_view(), name='exit_from_group'),
    path('wishlist/', include('wishlist.urls')),
    path('cloud/', include('cloud.urls')),
    path('calendar/', include('lightlist_calendar.urls')),
    path('change_password/', views.ChangePassword.as_view(), name='change_password'),
    path('kick_from_group/<int:member>', views.KickFromGroup.as_view(), name='kick_from_group'),
]

myapp/myapp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = ([
                   path('admin/', admin.site.urls),
                   path('', include('main.urls')),
                   # path('accounts/', include('django.contrib.auth.urls')),
                   # path('login/', include('main.urls')),
                   # path('registration/', include('main.urls')),
               ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
               + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

myapp/wishlist/urls.py
from django.urls import path
from . import views

urlpatterns = [
        path('', views.WishListMainPage.as_view(), name='wishlist'),
        path('<int:user>', views.WishListUser.as_view(), name='wishlistuser'),
        path('delete/<int:id>', views.WishDelete.as_view(), name='delete_wish'),
        path('change_active/<int:id>', views.WishChangeActive.as_view(), name='wish_change_active'),
        path('change_wish/<int:pk>', views.WishEdit.as_view(), name='wish_change_wish'),
]

myapp/cloud/models.py
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
from django.db import models
from main.models import Family


class CloudFile(models.Model):
    family = models.ForeignKey(Family, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now=True)
    video_file = models.FileField(upload_to='files/', null=True, blank=True, validators=[
        FileExtensionValidator(allowed_extensions=['mp4', 'mkv', 'mov', 'webm', 'avi'])])
    photo_file = models.FileField(upload_to='files/', null=True, blank=True, validators=[
        FileExtensionValidator(allowed_extensions=['jpg', 'png', 'ico', 'jpeg', 'bmp', 'webp'])])
    doc_file = models.FileField(upload_to='files/', null=True, blank=True, validators=[
        FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'odt', 'rtf', 'txt', 'ppt', 'pptx', 'xls', 'xlsx'])])
    archive_file = models.FileField(upload_to='files/', null=True, blank=True, validators=[
        FileExtensionValidator(allowed_extensions=['zip', 'rar', '7z', 'tar', 'gz'])])
    category = models.CharField(max_length=50, null=True, blank=True, choices=(('photo', 'Изображение'),
                                                                               ('doc', 'Документ'),
                                                                               ('archive', 'Архив'),
                                                                               ('video', 'Видео')))
    objects = models.Manager()

    class Meta:
        verbose_name = 'Файл'
        verbose_name_plural = 'Файлы'

    def __str__(self):
        if self.video_file:
            return f'{self.video_file}'
        elif self.photo_file:
            return f'{self.photo_file.name}'
        elif self.doc_file:
            return f'{self.doc_file.name}'
        elif self.archive_file:
            return f'{self.archive_file.name}'
        return f'Пустой файл'

myapp/main/models.py
from django.db import models
from django.core.validators import FileExtensionValidator, MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django import forms
from django.utils import timezone


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="userprofile")
    phoneNumber = models.DecimalField(max_digits=10, decimal_places=0, null=True, blank=True, name='phoneNumber')
    birthDate = models.DateField(null=True, blank=True, name='birthDate')
    patronimic = models.CharField(max_length=50, null=True, blank=True, name='patronimic')
    avatar = models.ImageField(
        upload_to=f'UserProfileImg',
        null=True,
        blank=True,
        validators=[FileExtensionValidator(allowed_extensions=['jpg', 'png', 'ico'])],
        name='profileAvatar'
    )
    familyIdentifierName = models.CharField(max_length=100, null=True, blank=True)
    family = models.ForeignKey('Family', on_delete=models.SET_NULL, blank=True, null=True, name='family')
    objects = models.Manager()

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'UserProfile'


class Family(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True, verbose_name='Название', name='name', unique=True)
    avatar = models.ImageField(
        upload_to=f'familyImg/',
        null=True,
        blank=True,
        validators=[FileExtensionValidator(allowed_extensions=['jpg', 'png', 'ico', 'jpeg', 'webp'])],
        verbose_name='Аватар',
        name='familyAvatar'
    )
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    objects = models.Manager()

    def __str__(self):
        if self.name is not None:
            return self.name
        return f'Семья №{self.id}'


class JoinFamilyRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    family = models.ForeignKey(Family, on_delete=models.CASCADE)
    accepted = models.BooleanField(default=False)
    objects = models.Manager()

    def __str__(self):
        if self.accepted:
            return f"{self.user} принят в {self.family}"
        else:
            return f"{self.user} хочет вступить в {self.family}"

    class Meta:
        verbose_name = 'Запрос'
        verbose_name_plural = 'Запросы'





@receiver(post_save, sender=User)
def createUserProfile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


@receiver(post_save, sender=User)
def saveUserProfile(sender, instance, **kwargs):
    instance.userprofile.save()

myapp/product_list/models.py
from django.db import models
from django.utils import timezone
from main.models import Family


class ProductListComponent(models.Model):
    family = models.ForeignKey(Family, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, verbose_name='Наименование')
    unit = models.CharField(max_length=2, choices=(('шт', 'шт'), ('кг', 'кг'), ('мл', 'мл'), ('уп', 'уп')),
                            verbose_name='Мера измерения')
    amount = models.FloatField(verbose_name='Количество')
    date = models.DateField(verbose_name='Дата добавления', default=timezone.now)
    objects = models.Manager()

    def __str__(self):
        return f"{self.name} - {self.amount} {self.unit} ({self.date})"

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

myapp/main/forms.py
import datetime

from django import forms
from django.core.validators import FileExtensionValidator
from django.utils import timezone

from .models import UserProfile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from .models import Family
from django.contrib.admin import widgets


class AddFamily(forms.ModelForm):
    class Meta:
        model = Family
        fields = ['name', 'familyAvatar']


class AddFamilyRequest(forms.Form):
    family = forms.TextInput(attrs={'class': 'form-control'})


class UpdateFamily(forms.ModelForm):
    class Meta:
        model = Family
        fields = ['name', 'familyAvatar']


class EditUserForm(forms.ModelForm):
    username = forms.CharField(max_length=191, required=False,
                               error_messages={
                                   'max_length': 'Длина должна быть меньше 191 символов',
                                   'unique': 'Это имя пользователя уже занято'
                               })
    first_name = forms.CharField(max_length=191, required=False,
                                 error_messages={
                                     'max_length': 'Длина должна быть меньше 191 символов'
                                 })
    last_name = forms.CharField(max_length=191, required=False,
                                error_messages={
                                    'max_length': 'Длина должна быть меньше 191 символов'
                                })

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name']


class EditProfileForm(forms.ModelForm):
    patronimic = forms.CharField(max_length=191, required=False,
                                 error_messages={
                                     'max_length': 'Длина должна быть меньше 191 символов'
                                 })
    profileAvatar = forms.ImageField(
        required=False,
        validators=[FileExtensionValidator(allowed_extensions=['jpg', 'png', 'ico'])],
    )

    birthDate = forms.DateField(required=False)

    class Meta:
        model = UserProfile
        fields = ['patronimic', 'profileAvatar', 'birthDate', 'phoneNumber']


class MyAuthenticationForm(AuthenticationForm):
    error_messages = {
        'invalid_login': (
            "Please enter a correct %(username)s and password. Note that both "
            "fields may be case-sensitive."
        ),
        'inactive': "This account is inactive.",
    }

myapp/product_list/forms.py
from django import forms
from . import models
class AddProduct(forms.ModelForm):
    class Meta:
        model = models.ProductListComponent
        fields = ['name', 'unit', 'amount']

myapp/wishlist/forms.py
from django import forms

from .models import WishListComponent


class WishListForm(forms.ModelForm):
    class Meta:
        model = WishListComponent
        exclude = ['date', 'user_profile']

myapp/product_list/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from . import forms
from main.models import UserProfile
from . import models


# Create your views here.
class ProductList(View):
    def get(self, request, *args, **kwargs):
        form = forms.AddProduct()
        products = models.ProductListComponent.objects.filter(family=UserProfile.objects.get(user=request.user).family)
        return render(request, 'main/product_list.html', {'form': form, 'products': products})

    def post(self, request, *args, **kwargs):
        form = forms.AddProduct(request.POST)
        if form.is_valid():
            new_prod = form.save(commit=False)
            new_prod.family = UserProfile.objects.get(user=request.user).family
            new_prod.save()
        return redirect('product_list')


class DeleteProduct(View):
    def get(self, request, *args, **kwargs):
        models.ProductListComponent.objects.filter(id=kwargs['id']).delete()
        return redirect('product_list')

myapp/wishlist/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.generic import View
from main.models import UserProfile
from .forms import WishListForm
from .models import WishListComponent


class WishListMainPage(View):
    def get(self, request, *args, **kwargs):
        ups = UserProfile.objects.filter(family=UserProfile.objects.get(user=request.user).family).filter(family__isnull=False)
        users = [up.user for up in ups]
        if request.user in users:
            users.insert(0, users.pop(users.index(request.user)))
        return render(request, 'main/wishlist.html', {'users': users})


class WishListUser(View):
    def get(self, request, *args, **kwargs):
        user = UserProfile.objects.get(user=kwargs['user'])
        showform = (request.user == user.user)
        if showform:
            wishes = WishListComponent.objects.filter(user_profile=user)
        else:
            wishes = WishListComponent.objects.filter(user_profile=user, active=True)
        form = WishListForm()
        return render(request, 'main/wishlist_user.html',
                      {'wishes': wishes, 'user_': user, 'form': form, 'showform': showform})

    def post(self, request, *args, **kwargs):
        form = WishListForm(request.POST, request.FILES)
        user = UserProfile.objects.get(user=request.user)
        wishes = WishListComponent.objects.filter(user_profile=user)
        showform = True
        if form.is_valid():
            wish = form.save(commit=False)
            wish.user_profile = UserProfile.objects.get(user=request.user)
            print(form.cleaned_data['wish_picture'])
            wish.save()
            print("Картинка пост", wish.wish_picture)
            print('err', form.errors)
            return JsonResponse({'status': 'ok'})
        else:
            return JsonResponse({'status': 'error', 'errors': form.errors})


class WishChangeActive(View):
    def get(self, request, *args, **kwargs):
        wish = WishListComponent.objects.get(id=kwargs['id'])
        wish.active = not wish.active
        wish.save()
        return redirect('wishlistuser', user=request.user.id)


class WishDelete(View):
    def get(self, request, *args, **kwargs):
        WishListComponent.objects.get(id=kwargs['id']).delete()
        return redirect('wishlistuser', user=request.user.id)


class WishEdit(View):
    def get(self, request, *args, **kwargs):
        wish = WishListComponent.objects.get(id=kwargs['pk'])
        return JsonResponse({'id_name': wish.name, 'id_url': wish.url,  'id_active': wish.active, 'id_reason': wish.reason, 'id_custom_reason': wish.custom_reason})

    def post(self, request, *args, **kwargs):
        wish = WishListComponent.objects.get(id=kwargs['pk'])
        form = WishListForm(request.POST, instance=wish)
        if form.is_valid():
            form.save()
            return JsonResponse({'status': 'ok'})
        return JsonResponse({'status': 'error', 'errors': form.errors})

myapp/main/templates/main/cloud_archive.html
{% extends 'main/htmlpatterns.html' %}
{% load static %}

{% block title %} Облако вашей группы - Архивы {% endblock %}

{% block mainContent %}

<script>
    window.onload = function (){
        $('#file_delete').click(function (){
            var todelete = new Map()
            console.log('clicked')
            $('input[type=checkbox]').each(function(index,element){
                todelete.set(element.id, element.checked)
            })
            console.log(JSON.stringify(Object.fromEntries(todelete), null,  '\t'))
            $.post('{% url "delete_cloud_batch_archive" %}', { 'data':JSON.stringify(Object.fromEntries(todelete)) }, function(data){
                window.location.reload()
            })
        })
    }
</script>
<div class="container">
    <div class="col">
            <button class="fill-danger p-2" id="file_delete">Удалить выбранные</button>
    </div>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 row-cols-xxl-6">
        <div class="col">
            <div class="card mt-3">
                <div class="card-header text-center bg-custom-color-light">
                    <img src="{% url 'thumbnails' %}?cat=add" class="img-thumbnail">
                </div>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card-body py-4">
                        <input type="file" name="archive_file" id="id_archive_file" class="form-control" accept=".zip, .rar, .7z, .tar, .gz">
                    </div>
                    <div class="card-footer bg-custom-color-dark text-center">
                        <button type="submit" class="fill-light mb-0 py-2">Загрузить</button>
                    </div>
                </form>
            </div>
        </div>
        {% for f, n, e in files %}
        <div class="col">
            <div class="card mt-3">
                <div class="card-header text-center bg-custom-color-light">
                   <img src="{% url 'thumbnails' %}?ext={{ e }}&cat=archive" class="img-thumbnail">
                </div>
                <div class="card-body text-center">
                    <a class="underline-one" href="{% url 'cloud_storage' %}?path={{ n }}" download>
                        {{ n }}
                    </a>
                </div>
                <div class="card-footer bg-custom-color-dark">
                    <div class="row align-items-center">
                        <div class="col-2">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="" id="{{ f.id }}">
                            </div>
                        </div>
                        <div class="col-5">
                            <a  href="{% url 'cloud_storage' %}?path={{ n }}">
                                <button class="fill-light m-1 p-2 border-2">
                                    <i class="material-icons-size-3 p-0">slideshow</i>
                                </button>
                            </a>
                        </div>
                        <div class="col-5">
                            <a href="{% url 'delete_cloud_archive' f.id %}">
                                <button class="fill-danger m-1 p-2 border-2">
                                    <i class="material-icons-size-2 p-0">delete_forever</i>
                                </button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

myapp/main/templates/main/editprofile.html
{% extends 'main/htmlpatterns.html' %}
{% load static %}

{% block title %} Редактирование профиля {% endblock %}

{% block mainContent %}
<link rel="stylesheet" href="{% static 'main/css/editprofile.css' %}">

<div class="container d-flex justify-content-center">
    <div class="card border rounded-2 shadow col-sm-12 col-md-10 col-lg-10 col-xl-10 col-xxl-10">
        <div class="card-header bg-color">
            <p class="display-6 text-color text-center">Редактирование профиля</p>
        </div>
        <div class="row">
            <div class="col-3">
                <div class="card-block bg-color d-flex justify-content-center p-3">
                    <div class="container-fluid">
                        <div class="row px-3 pt-4">
                            {% if user.userprofile.profileAvatar %}
                            <img src="{{ BASE_DIR }}/media/{{ user.userprofile.profileAvatar }}"
                                 class="rounded-circle" alt="Лого">
                            {% else %}
                            <img src="{% static 'main/img/profileDefault.png' %}" class="rounded-circle"
                                 alt="Лого">
                            {% endif %}
                        </div>
                        <div class="row pt-4 text-center">
                            <p class="h4 text-color">{{ user.username }}</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-9">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card-block d-flex align-items-center">
                        <div class="container-fluid">
                            <div class="row pt-3">
                                <div class="col-3 align-self-center">
                                    <p class="h5 col">Никнейм:</p>
                                </div>
                                <div class="col-9">
                                    <div class="col-11">
                                        <input class="form-control" type="text" name="username" id="id_username"
                                               {% if user.username %} value="{{ user.username }}" {% endif %}>
                                    </div>
                                </div>
                            </div>
                            <div class="row pt-3">
                                <div class="col-3 align-self-center">
                                    <p class="h5 col">Фамилия:</p>
                                </div>
                                <div class="col-9">
                                    <div class="col-11">
                                        <input class="form-control" type="text" name="last_name" id="id_last_name"
                                               {%  if user.last_name %} value="{{ user.last_name }}" {% endif %}>
                                    </div>
                                </div>
                            </div>
                            <div class="row pt-3">
                                <div class="col-3 align-self-center">
                                    <p class="h5 col">Имя:</p>
                                </div>
                                <div class="col-9">
                                    <div class="col-11">
                                        <input class="form-control" type="text" name="first_name" id="id_first_name"
                                               {% if user.first_name %} value="{{ user.first_name }}" {% endif %}>
                                    </div>
                                </div>
                            </div>
                            <div class="row pt-3">
                                <div class="col-3 align-self-center">
                                    <p class="h5 col">Отчество:</p>
                                </div>
                                <div class="col-9">
                                    <div class="col-11">
                                        <input class="form-control" type="text" name="patronimic" id="id_patronimic"
                                               {% if user.userprofile.patronimic %} value="{{ user.userprofile.patronimic }}" {% endif %}>
                                    </div>
                                </div>
                            </div>
                            <div class="row pt-3">
                                <div class="col-3 align-self-center">
                                    <p class="h5 col">Дата рождения:</p>
                                </div>
                                <div class="col-9">
                                    <div class="col-11">
                                        <input class="form-control" type="date" name="birthDate" id="id_birthDate"
                                               value="{{ user.userprofile.birthDate|date:'Y-m-d' }}">
                                    </div>
                                </div>
                            </div>
                            <div class="row pt-3">
                                <div class="col-3 align-self-center">
                                    <p class="h5 col">Номер телефона:</p>
                                </div>
                                <div class="col-9">
                                    <div class="col-11">
                                        <div class="input-group">
                                            <span class="input-group-text">+7</span>
                                        <input class="form-control" type="text" name="phoneNumber"
                                               id="id_phoneNumber" {% if user.userprofile.phoneNumber %} value="{{ user.userprofile.phoneNumber }}" {% endif %}>
                                        </div>
            
                                    </div>
                                </div>
                            </div>
                            <div class="row pt-3">
                                <div class="col-3 align-self-center">
                                    <p class="h5 col">Аватар:</p>
                                </div>
                                <div class="col-9">
                                    <div class="col-11">
                                        <input class="form-control" type="file" name="profileAvatar"
                                               id="id_profileAvatar" accept=".jpg, .jpeg, .png, .webp, .ico">
                                    </div>
                                </div>
                            </div>
                            <div class="row pt-3">
                                <div class="col-3 align-self-center">
                                    <p class="h5 col">Пароль:</p>
                                </div>
                                <div class="col-9">
                                    <div class="col-11">
                                        <button type="button" class="fill-primary mx-2 py-2" data-bs-toggle="modal"
                                                data-bs-target="#exampleModal">
                                            Сменить пароль
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <div class="row pt-3 pb-3">
                                <div class="col-11 d-flex justify-content-center">
                                    <button class="fill-success mx-2" type="submit">Сохранить</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Смена пароля</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="change_password_form">
                    {% csrf_token %}
                    <label for="id_old_password">Старый пароль:</label>
                    <input type="password" name="old_password" autocomplete="current-password" autofocus="" required=""
                           id="id_old_password" class="form-control pt-2">
                    <label for="id_new_password1">Новый пароль:</label>
                    <input type="password" name="new_password1" autocomplete="new-password" required=""
                           aria-describedby="id_new_password1_helptext" id="id_new_password1" class="form-control pt-2">

                    <span class="helptext" id="id_new_password1_helptext"></span>
                    <label for="id_new_password2">Подтверждение нового пароля:</label>
                    <input type="password" name="new_password2" autocomplete="new-password" required=""
                           id="id_new_password2" class="form-control">
                </form>
                <ul class="list-group py-3 opacity-75">
                    <li class="list-group-item">Пароль не должен быть слишком похож на другую вашу личную
                        информацию.
                    </li>
                    <li class="list-group-item">Ваш пароль должен содержать как минимум 8 символов.</li>
                    <li class="list-group-item">Пароль не должен быть слишком простым и распространенным.</li>
                    <li class="list-group-item">Пароль не может состоять только из цифр.</li>
                </ul>
            </div>
            <div class="modal-footer">
                <button type="button" class="fill-success" id="change_password">Сохранить</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function(){
        $('#change_password').click(function (){
            let form_data = $('#change_password_form').serialize()

            $.ajax({
                type: "POST",
                url: "{% url 'change_password' %}",
                data: form_data,
                success: function (data) {
                    $('.invalid-feedback').remove()
                    $('.is-invalid').removeClass('is-invalid')
                    if(data['status']=='ok')
                    {
                        $('#id_old_password').val("")
                        $('#id_new_password1').val("")
                        $('#id_new_password2').val("")
                        location.replace("/%2Flogin")
                    }
                    else{

                        for(let e in data['errors'])
                        {
                            $('#id_'+e).addClass('is-invalid')
                            $('#id_'+e).after(`<div class="invalid-feedback">${data['errors'][e]}</div>`)
                        }
                    }
                }
            })

        })
    })

</script>
{% endblock %}